### ISSUE TITLE
Middle Earth Dataset For My Project 

### ISSUE THREAD

**Issue by ezgiturali** [jvangeld/ME-GIS#14]
Hello dear friend,
I am a master student of applied data science program in TED University. I have a term project for statistical inference and my aim is to build a Middle Earth map as a dashboard in R. I would like to present the story line in that map. Therefore, I would like to use your dataset. Can I get your dataset for this purpose? If you like I would share it with you :)

Thank you for your interest!
Happy Coding.

**Comment by jvangeld** [comment]
Have at it!
