### ISSUE TITLE
Permission to use the data for promotional purposes by a company

### ISSUE THREAD

**Issue by suavecb** [jvangeld/ME-GIS#28]
Hi,
I'm a manager in GIS/AI software company (http://www.wizipisi.pl/en/). Me and some of my colleagues are heavily into Tolkien's world and we had the idea to collect available vector data + raster data + dbpedia + wikidata, perform some GIS/NLP/Graph analyses and see if we can extract some cool infomration (new facts, relations etc.) and then show it on the maps. Our goal is simply to have fun, but we also want to share it in the social media (linkedin/facebook etc.) from time to time, to share our company culture.  Can we use the data you've created for these purposes? All of the credits will of course be included and we can share the results of our analyses here.

**Comment by ghost** [comment]
Sure, you may.
